src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    const REGISTRO_EXITOSO = 'Fue registrado con exito';

    public function __construct()
    {
        $this->baneado = false;
        $this->roles   = ['ROLE_USER'];
    }

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Profesion", mappedBy="user")
     */
    private $profesion;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Posts", mappedBy="user")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comentarios", mappedBy="user")
     */
    private $comentarios;


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $nombre;


    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    public $baneado;


    public function getBaneado() : ? boolean
    {
        return $this->baneado;
    }


    public function setBaneado($baneado): self
    {
        $this->baneado = $baneado;
        return $this;
    }


    public function getNombre() : ?string
    {
        return $this->nombre;
    }


    public function setNombre($nombre): self
    {
        $this->nombre = $nombre;
        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return array_unique($this->roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Symfony Blog {% endblock %}</title>
        {% block stylesheets %}
            <link rel="icon" href="https://getbootstrap.com/docs/4.0/assets/img/favicons/favicon.ico">
            <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
            <link href="https://getbootstrap.com/docs/4.0/examples/blog/blog.css" rel="stylesheet">
            <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
            <link href="{{ asset('css/style.css' ) }}" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
        {% block body %}


            {% if app.user %}
                <div class="container">
                    <header class="blog-header py-3">
                        <div class="row flex-nowrap justify-content-between align-items-center">
                            <div class="col-4 pt-1">
                                <div class=""><i class="fa fa-user" aria-hidden="true"></i> {{ app.user.username }} </div>
                            </div>
                            <div class="col-4 text-center">
                                <a class="blog-header-logo text-dark" href="/">Symfony Blog</a>
                            </div>
                            <div class="col-4 d-flex justify-content-end align-items-center">
                                <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_logout') }}"><i class="fa fa-sign-out"></i> Salir</a>
                            </div>
                        </div>
                    </header>
                    <div class="nav-scroller py-1 mb-2">
                        <nav class="nav d-flex justify-content-between">
                            <a class="p-2 text-muted" href="{{ path('crear_post') }}">Crear publicación</a>
                            <a class="p-2 text-muted" href="{{ path('my_posts') }}">Mis publicaciones</a>
                        </nav>
                    </div>
                </div>
            {% else %}
                <div class="container">
                    <header class="blog-header py-3">
                        <div class="row flex-nowrap justify-content-between align-items-center">
                            <div class="col-4 pt-1">
                                <a class="btn btn-sm btn-outline-secondary" href="{{ path('registro') }}"><i class="fa fa-user" aria-hidden="true"></i> Registrase</a>
                            </div>
                            <div class="col-4 text-center">
                                <a class="blog-header-logo text-dark" href="/">Symfony Blog</a>
                            </div>
                            <div class="col-4 d-flex justify-content-end align-items-center">
                                <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_login') }}"><i class="fa fa-sign-in" aria-hidden="true"></i> Entrar</a>
                            </div>
                        </div>
                    </header>
                </div>
            {% endif %}

        {% endblock %}

        <footer class="blog-footer footer">
            <p><a href="/">Symfony</a></p>
        </footer>

        {% block javascripts %}
            <script type='text/javascript' src='https://suzdalenko.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp'></script>
            <script type='text/javascript' src='https://suzdalenko.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
            <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
            <script src="{{ asset('js/ajax.js' ) }}"></script>
        {% endblock %}
    </body>
</html>